hero/HTML
TarasTikan/team-7 pull request #4
Opened 2022-09-17 11:20 UTC by VozzRoman

я там добавил картинки и два спрайта

2022-09-17 12:51 UTC, TarasTikan requested changes

2022-09-17 12:51 UTC, TarasTikan commented on src/partials/hero-header.html
> +				<h1 class="section-hero__title section-hero__title--size">passion</h1>
чого в тебе відділені заголовки? Зроби один заголовок

2022-09-17 12:51 UTC, TarasTikan commented on src/partials/hero-header.html
> +							<div class="hero-item__number">16</div>
тут тег `span`, замість діва

2022-09-17 12:51 UTC, TarasTikan commented on src/partials/hero-header.html
> +							<div class="hero-item__text">cafes</div>
тут тег`p`

2022-09-17 12:51 UTC, TarasTikan commented on src/partials/hero-header.html
> +							<div class="hero-item__number">23</div>
тут тег `span`, замість діва

2022-09-17 12:51 UTC, TarasTikan commented on src/partials/hero-header.html
> +							<div class="hero-item__text">food trucks</div>
тут тег `p`

2022-09-17 12:54 UTC, TarasTikan commented on src/partials/hero-header.html
> +							<div class="hero-item__text">food trucks</div>
чому ти кожин `picture` обгорнув в дів, єслі тег `picture` теж контейнер, йому я думаю возможно ставити класи.

2022-09-17 12:55 UTC, TarasTikan commented on src/partials/hero-header.html
> +							<div class="hero-item__text">food trucks</div>
Ще потрібно викачати 2x зоображення і вставити. В тебе тільки 1x.

2022-09-17 13:26 UTC, TarasTikan commented on src/partials/hero-header.html
> +							<div class="hero-item__text">food trucks</div>
ще поміняй в названіях замість `section-hero__iteam` на `section__hero__iteam` отак у всіх щоб було нижнє підчеркування

2022-09-17 15:37 UTC, VozzRoman commented on src/partials/hero-header.html
> +				<h1 class="section-hero__title section-hero__title--size">passion</h1>
там в одно заголовке разный шрифт! поэтому два заголовка

2022-09-17 15:40 UTC, VozzRoman commented on src/partials/hero-header.html
> +							<div class="hero-item__number">16</div>
исправил

2022-09-17 15:40 UTC, VozzRoman commented on src/partials/hero-header.html
> +							<div class="hero-item__text">cafes</div>
исправил

2022-09-17 15:40 UTC, VozzRoman commented on src/partials/hero-header.html
> +							<div class="hero-item__number">23</div>
исправил

2022-09-17 15:50 UTC, VozzRoman commented on src/partials/hero-header.html
> +							<div class="hero-item__text">food trucks</div>
насчет picture да согласен можно калсс дать так и хотел сделать! но сделал как принимал ментор в прошлом макете да и помню когда разбирал эту тему с адаптивными картинками то в большинстве случаях  picture идет отдельно без класса, типа так безопасней

2022-09-18 08:10 UTC, TarasTikan requested changes

2022-09-18 08:10 UTC, TarasTikan commented on src/partials/hero-header.html
> +				<h1 class="section-hero__title">ice cream made with <span>passion</span></h1>
спану ти не додав клас

2022-09-18 08:54 UTC, TarasTikan approved these changes

2022-09-18 09:02 UTC, TarasTikan approved these changes

2022-09-18 09:03 UTC, merged